version: '3'

volumes:
  pg_data1:


services:
  database:
    image: postgres:16
    environment:
      - DB_HOST=localhost
      - DB_PORT=6000
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pg_data1:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:6000:6000'
    command: -p 6000